action_id: trunk-single-player-auto-upgrade
date: 2026-06-08 22:40:59
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1780958459
full_timestamp:
  nanos: 392615000
  seconds: 1780958459
trunk_version: 1.25.0
