action_id: trunk-single-player-auto-upgrade
date: 2026-06-07 10:00:49
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1780826449
full_timestamp:
  nanos: 72958000
  seconds: 1780826449
trunk_version: 1.25.0
