action_id: trunk-cache-prune
date: 2026-06-08 06:43:19
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1780900999
full_timestamp:
  nanos: 473011000
  seconds: 1780900999
trunk_version: 1.25.0
