action_id: trunk-cache-prune
date: 2026-06-08 09:01:52
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1780909312
full_timestamp:
  nanos: 121025000
  seconds: 1780909312
trunk_version: 1.25.0
