action_id: trunk-cache-prune
date: 2026-06-08 21:41:05
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1780954865
full_timestamp:
  nanos: 214301000
  seconds: 1780954865
trunk_version: 1.25.0
