name: nox_root
description: Root-level test utilities for the NOX project.
publish_to: none
version: 0.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
