@echo off
REM Generated by trunk tool 'actionlint'
set PATH=C:\Users\pyaip\AppData\Local\trunk\tools\actionlint\1.7.12-a1b92580bf049660c647af0595701219;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b actionlint %*
