@echo off
REM Generated by trunk tool 'eslint'
set NODE_PATH=C:\Users\pyaip\AppData\Local\trunk\tools\eslint\8.57.0-e038d0e4bf117c8e145f23841d63b53d/node_modules
set PATH=C:\Users\pyaip\AppData\Local\trunk\tools\eslint\8.57.0-e038d0e4bf117c8e145f23841d63b53d/node_modules/.bin;C:\Users\pyaip\AppData\Local\trunk\tools\node\22.16.0-12da8a4c27b144aedaf7d975e067667c/bin;C:\Users\pyaip\AppData\Local\trunk\tools\node\22.16.0-12da8a4c27b144aedaf7d975e067667c;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=

start /w /b eslint %*
