@echo off
REM Generated by trunk tool 'grype'
set PATH=C:\Users\pyaip\AppData\Local\trunk\tools\grype\0.115.0-913da66dd205a3bb758ee5280f901adb;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b grype %*
