@echo off
REM Generated by trunk tool 'hadolint'
set PATH=C:\Users\pyaip\AppData\Local\trunk\tools\hadolint\2.14.0-45aceb05a52315ca4900460125f7f0d9;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b hadolint %*
