@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\pyaip\AppData\Local\trunk\tools\osv-scanner\2.3.8-dc2749505c1fa56202a84ecfeea0f227;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
