@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\pyaip\AppData\Local\trunk\tools\osv-scanner\2.4.0-bb19bbcf631d775b2dd07dbcbbbe931c;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
