@echo off
REM Generated by trunk tool 'pinact'
set PATH=C:\Users\pyaip\AppData\Local\trunk\tools\pinact\4.0.0-e606c84de429d065494ef4161f3480f5;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b pinact %*
