@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\pyaip\AppData\Local\trunk\tools\trufflehog\3.95.5-717a9aeca7bc7a62dd12a647cea7ad2f;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
