@echo off
REM Generated by trunk tool 'yamllint'
set PYTHONUTF8=1
set PATH=C:\Users\pyaip\AppData\Local\trunk\tools\yamllint\1.38.0-660682d783cf76ba864bf631359061b7/bin;C:\Users\pyaip\AppData\Local\trunk\tools\yamllint\1.38.0-660682d783cf76ba864bf631359061b7/Scripts;C:\Users\pyaip\AppData\Local\trunk\tools\python\3.14.4-cb3a144a569cdde1b1583669bb421ff0/bin;C:\Users\pyaip\AppData\Local\trunk\tools\python\3.14.4-cb3a144a569cdde1b1583669bb421ff0;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\pyaip\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set VIRTUAL_ENV=C:\Users\pyaip\AppData\Local\trunk\tools\yamllint\1.38.0-660682d783cf76ba864bf631359061b7

start /w /b yamllint %*
