action_id: trunk-whoami
date: 2026-06-08 22:41:06
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Not logged in. Run \"trunk login\" to login\x1b[0m\r\n"
  err: ""
timestamp: 1780958466
full_timestamp:
  nanos: 883687000
  seconds: 1780958466
trunk_version: 1.25.0
