action_id: trunk-upgrade-available
date: 2026-06-09 01:40:57
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\KeIxG.yaml for details.
  error_path: C:\Users\pyaip\OneDrive\NOX\.trunk\out\KeIxG.yaml
timestamp: 1780969257
full_timestamp:
  nanos: 75020000
  seconds: 1780969257
trunk_version: 1.25.0
