name: nox_flutter_app
description: Main Flutter application package for the NOX multi-package monorepo.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  go_router: ^17.2.3
  nox_flutter_core:
    path: ../core
  nox_flutter_features:
    path: ../features
  nox_flutter_shared:
    path: ../shared

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
