name: nox_flutter_core
description: Core utilities and infrastructure for NOX Flutter applications.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.2.0
  flutter_secure_storage: ^9.0.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
